//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BTL_nhom2_demo.DTO
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QLBH_01Entities : DbContext
    {
        public QLBH_01Entities()
            : base("name=QLBH_01Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<tb_Calam> tb_Calam { get; set; }
        public virtual DbSet<tb_Congviec> tb_Congviec { get; set; }
        public virtual DbSet<tb_CTHDB> tb_CTHDB { get; set; }
        public virtual DbSet<tb_CTHDN> tb_CTHDN { get; set; }
        public virtual DbSet<tb_Donvitinh> tb_Donvitinh { get; set; }
        public virtual DbSet<tb_Hanghoa> tb_Hanghoa { get; set; }
        public virtual DbSet<tb_HDB> tb_HDB { get; set; }
        public virtual DbSet<tb_HDN> tb_HDN { get; set; }
        public virtual DbSet<tb_Khachhang> tb_Khachhang { get; set; }
        public virtual DbSet<tb_Loaihang> tb_Loaihang { get; set; }
        public virtual DbSet<tb_NCC> tb_NCC { get; set; }
        public virtual DbSet<tb_Nhanvien> tb_Nhanvien { get; set; }
    }
}
