//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BTL_nhom2_demo.DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_HDB
    {
        public int ma_hdb { get; set; }
        public Nullable<int> ma_nv { get; set; }
        public Nullable<System.DateTime> ngay_ban { get; set; }
        public Nullable<int> ma_kh { get; set; }
        public Nullable<double> thanh_tien { get; set; }
    
        public virtual tb_CTHDB tb_CTHDB { get; set; }
        public virtual tb_Khachhang tb_Khachhang { get; set; }
        public virtual tb_Nhanvien tb_Nhanvien { get; set; }
    }
}
