//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BTL_nhom2_demo.DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Hanghoa
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_Hanghoa()
        {
            this.tb_CTHDB = new HashSet<tb_CTHDB>();
            this.tb_CTHDN = new HashSet<tb_CTHDN>();
        }
    
        public int ma_hang { get; set; }
        public string ten_hang { get; set; }
        public Nullable<int> ma_loai { get; set; }
        public Nullable<int> ma_nuoc { get; set; }
        public Nullable<double> so_luong { get; set; }
        public Nullable<double> don_gia_nhap { get; set; }
        public Nullable<double> don_gia_ban { get; set; }
        public string thoi_gian_bh { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_CTHDB> tb_CTHDB { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_CTHDN> tb_CTHDN { get; set; }
        public virtual tb_Loaihang tb_Loaihang { get; set; }
        public virtual tb_Xuatxu tb_Xuatxu { get; set; }
    }
}
