//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BTL_nhom2_demo.DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_NCC
    {
        public int ma_ncc { get; set; }
        public string ten_ncc { get; set; }
        public string dia_chi { get; set; }
        public string dien_thoai { get; set; }
    }
}
